milotest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path

from users.views import UserList, UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, exportToCSV

app_name='users'
urlpatterns = [
    path('', UserList.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/create', UserCreateView.as_view(), name='user-create'),
    path('user/update/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user-delete'),
    path('export', exportToCSV, name='user-export'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import random

class CustomUser(AbstractUser):
    # First/last name is not a global-friendly pattern
    # name = models.CharField(blank=True, max_length=255)
    birth_date = models.DateField(null=True, blank=True)
    random_number = models.IntegerField(default=random.randint(1,101))

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from .models import CustomUser
from django import forms

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password', 'birth_date']
        widgets = {
            'password': forms.PasswordInput(),
            'birth_date': forms.SelectDateWidget(years=range(1900, 2018)),
        }

users/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import (CreateView, DeleteView, UpdateView)
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django import forms
import csv

from users.templatetags.user_filters import allowed, bizzfuzz
from .models import CustomUser
from .forms import CreateUserForm

class UserList(ListView):
    model = CustomUser

class UserDetailView(DetailView):
    model = CustomUser

class UserCreateView(CreateView):
    form_class = CreateUserForm
    model = CustomUser
    success_url = reverse_lazy('users:user-list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        print(self.object.password)
        self.object.set_password(self.object.password)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class UserUpdateView(UpdateView):
    form_class = CreateUserForm
    model = CustomUser
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('users:user-list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['password'].widget = forms.PasswordInput()
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        print(self.object.password)
        self.object.set_password(self.object.password)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class UserDeleteView(DeleteView):
    model = CustomUser
    success_url = reverse_lazy('users:user-list')


def exportToCSV(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="milotest.csv"'

    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Eligible', 'Random Number', 'BizzFuzz'])

    users = CustomUser.objects.all()
    for user in users:
        writer.writerow([user.username, user.birth_date, allowed(user.birth_date), user.random_number, bizzfuzz(user.random_number)])

    return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Milo Test App</title>

    {% block head %}{% endblock %}

</head>
<body>
    <h1>{% block title %}{% endblock %}</h1>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/users/customuser_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete User{% endblock %}

{% block content %}
    <p><a href="{% url 'users:user-list' %}">Cancel</a></p>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.username }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

templates/users/customuser_detail.html
{% extends 'base.html' %}

{% block title %}User {{ object.username }}{% endblock %}

{% block content %}
    <p><a href="{% url 'users:user-list' %}">Back</a></p>
    <p><strong>Email:</strong> {{ object.email }}</p>
    <p><strong>Birth date:</strong> {{ object.birth_date }}</p>
    <p><strong>Random number:</strong> {{ object.random_number }}</p>
{% endblock %}

templates/users/customuser_form.html
{% extends 'base.html' %}

{% block title %}Create User{% endblock %}

{% block content %}
    <p><a href="{% url 'users:user-list' %}">Back</a></p>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

templates/users/customuser_list.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}Users{% endblock %}

{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock %}

{% block content %}
    <p><a href="{% url 'users:user-create' %}">Create</a> <a href="{% url 'users:user-export' %}">Export to CSV</a></p>
    <div>
        <span class="col header">Username</span>
        <span class="col header">Birthday</span>
        <span class="col header">Eligible</span>
        <span class="col header">Random Number</span>
        <span class="col header">BizzFuzz</span>
    </div>
    {% for user in object_list %}
        <div>
            <span class="col"><a href="{% url 'users:user-detail' user.id %}">{{user.username}}</a></span>
            <span class="col">{{ user.birth_date }}</span>
            <span class="col">{{ user.birth_date | allowed }}</span>
            <span class="col">{{ user.random_number }}</span>
            <span class="col">{{ user.random_number | bizzfuzz }}</span>
            <span class="col">
                <a href="{% url 'users:user-update' user.id %}">Edit</a>
                <a href="{% url 'users:user-delete' user.id %}">Delete</a>
            </span>
        </div>
    {% empty %}
        <div>No users.</div>
    {% endfor %}
{% endblock %}

templates/users/customuser_update_form.html
{% extends 'base.html' %}

{% block title %}Update User{% endblock %}

{% block content %}
    <p><a href="{% url 'users:user-list' %}">Back</a></p>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

templates/users/list.html
{% extends 'base.html' %}

{% block title %}Users list{% endblock %}

{% block content %}
    {% for user in users %}
        {{user.email}}
    {% endfor %}
{% endblock %}